sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 10
os:
  - linux
before_script:
  - npm i
  - cd examples
  - node ../packages/cli/bin/demobook -o hiroppy -r demobook -t https://demobook-ci.herokuapp.com -d output
